version: '3.0'

services:
  openapi_mock:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: 'https://glennreilly.github.io/test2.yaml'
      OPENAPI_MOCK_USE_EXAMPLES: 'if_present'
    ports:
      - "8080:8080"
