'openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /getHomeScreenFeed:
    get:
      summary: Returns an example Home screen feed json
      responses:
        '200':
          description: a example feed json is returned
          content:
            application/json:
              schema:
                type: string
                example: >
                hello

  /getAString:
    get:
      summary: Returns an example String
      responses:
        '200':
          description: a example string
            application/json:
              schema:
                type: string
                example: "This is a string"

  /list:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response

  /getAnArtist:
    get:
      summary: Returns an artist
      responses:
        '200':
          description: an artist is returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  artist_name:
                    type: string
                  artist_genre:
                    type: string
                  albums_recorded:
                    type: integer

  /getANumber:
    get:
      summary: Returns a number betwixt x and y
      responses:
        '200':
          description: a number is returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: integer
                    minimum: -10
                    maximum: 50

  /getAnotherNumber:
    get:
      summary: Returns a number betwixt x and y
      responses:
        '200':
          description: a number is returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: integer
                    minimum: -10
                    maximum: 50
                    example: 42
'
